### ISSUE TITLE
Random Matrix Theory

### ISSUE THREAD

**Issue by irregular-rhomboid** [irregular-rhomboid/EAI-Math-Reading-Group#3]
RMT is a famously tough topic that has found a couple of interesting applications in ML (see e.g. Greg Yang's work)

A possible source could be [this book](https://www.cambridge.org/core/books/first-course-in-random-matrix-theory/2292A554A9BB9E2A4697C35BCE920304#fndtn-information), but I don't have a "freely" available pdf for it yet. The other sources I have seem a bit too difficult.

**Comment by fecet** [comment]
https://www.math.uci.edu/~rvershyn/papers/HDP-book/HDP-book.html could be a good one to start

**Comment by irregular-rhomboid** [comment]
> https://www.math.uci.edu/~rvershyn/papers/HDP-book/HDP-book.html could be a good one to start

This is cool, but probably too advanced for the typical audience of the group. (Adding it to my digital pile though. Thanks :smile: )
Anyway, we did find a pdf of the first book, so we're good on that.
